// Generated by reader_util_test.go.
// Only edit to bootstrap new entries or change existing entries.

package fit_test

var decodeTestFiles = [...]struct {
	folder      string
	name        string
	wantErr     bool
	fingerprint uint64
	compress    bool
	dopts       testingDecodeOpts
	skipEncode  bool
}{
	{
		"me",
		"activity-small-fenix2-run.fit",
		false,
		15371287692040796867,
		true,
		tdoAllWithDiscardLogger,
		true, // Decode mismatch due to unknown fields
	},
	{
		"fitsdk",
		"Activity.fit",
		false,
		16564348327836914264,
		true,
		tdoNone,
		false,
	},
	{
		"fitsdk",
		"MonitoringFile.fit",
		false,
		2061789885649091689,
		true,
		tdoNone,
		true, // Fails because first message has different valid fields (#36)
	},
	{
		"fitsdk",
		"Settings.fit",
		false,
		3764513367232478449,
		true,
		tdoNone,
		false,
	},
	{
		"fitsdk",
		"WeightScaleMultiUser.fit",
		false,
		11646130095806592003,
		true,
		tdoNone,
		false,
	},
	{
		"fitsdk",
		"WorkoutCustomTargetValues.fit",
		false,
		4975066257479915757,
		true,
		tdoNone,
		false,
	},
	{
		"fitsdk",
		"WorkoutIndividualSteps.fit",
		false,
		17191203419508130426,
		true,
		tdoNone,
		false,
	},
	{
		"fitsdk",
		"WorkoutRepeatGreaterThanStep.fit",
		false,
		15582330408656848122,
		true,
		tdoNone,
		false,
	},
	{
		"fitsdk",
		"WorkoutRepeatSteps.fit",
		false,
		1094841760112654858,
		true,
		tdoNone,
		false,
	},
	{
		"fitsdk",
		"WeightScaleSingleUser.fit",
		false,
		2611280041225851776,
		true,
		tdoNone,
		false,
	},
	{
		"python-fitparse",
		"garmin-edge-500-activitiy.fit",
		false,
		187062999533099257,
		true,
		tdoNone,
		false,
	},
	{
		"python-fitparse",
		"sample-activity-indoor-trainer.fit",
		false,
		17257111721631779652,
		true,
		tdoNone,
		true, // Fails because first message has different valid fields (#36)
	},
	{
		"python-fitparse",
		"compressed-speed-distance.fit",
		false,
		0,
		false,
		tdoNone,
		false,
	},
	{
		"python-fitparse",
		"antfs-dump.63.fit",
		false,
		501629305333581,
		true,
		tdoNone,
		true, // Fails because first message has different valid fields (#36)
	},
	{
		"sram",
		"Settings.fit",
		false,
		5227529081664738551,
		true,
		tdoNone,
		true, // Fails due to encoder using profile length for arrays (#37)
	},
	{
		"sram",
		"Settings2.fit",
		false,
		4224699768017778451,
		true,
		tdoNone,
		true, // Fails due to encoder using profile length for arrays (#37)
	},
	{
		"dcrainmaker",
		"Edge810-Vector-2013-08-16-15-35-10.fit",
		false,
		1609778763665414357,
		true,
		tdoNone,
		true, // Fails because first message has different valid fields (#36)
	},
	{
		"misc",
		"2013-02-06-12-11-14.fit",
		false,
		17117524088678637721,
		true,
		tdoNone,
		false,
	},
	{
		"misc",
		"2015-10-13-08-43-15.fit",
		false,
		866668951188110197,
		true,
		tdoNone,
		false,
	},
	{
		"corrupt",
		"activity-filecrc.fit",
		true,
		9805540585987241397,
		true,
		tdoNone,
		false,
	},
	{
		"corrupt",
		"activity-unexpected-eof.fit",
		true,
		15570394638376952680,
		true,
		tdoNone,
		false,
	},
}
